version: '3'

services:
  reporting:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    container_name: reporting
    volumes:
      - .:/app
    ports:
      - "8800:8000"
    networks:
      - topline-environment_default

networks: 
  topline-environment_default:
    external: true