version: '3'

services:
  report:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    container_name: report
    volumes:
      - .:/app
    ports:
      - "8800:8000"