version: '3'

services:

  reporting:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    container_name: trood-reporting
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - trood-network

networks:
  trood-network:
    driver: bridge
