# Generated by Django 2.2 on 2019-04-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title', max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Created')),
                ('deleted', models.DateTimeField(blank=True, help_text='Deleted', null=True)),
                ('type', models.CharField(choices=[('PSQL', 'PostgreSQL'), ('DRUID', 'Druid')], help_text='Source type', max_length=16)),
                ('dsn', models.CharField(help_text='Source connection string', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title', max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('edited', models.DateTimeField(auto_now=True, help_text='Created')),
                ('deleted', models.DateTimeField(blank=True, help_text='Deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text='Code', max_length=128, unique=True)),
                ('query', models.TextField(help_text='Query string')),
                ('source', models.ForeignKey(help_text='Report source', on_delete=django.db.models.deletion.CASCADE, to='trood_reporting.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
